site_name: PS is not Physical Simulation
site_url: https://adversarr.github.io/ps/
nav:
  - Home: index.md
  - Papers: Papers/index.md
  - Registry: registry.md
  - Tags: tags.md
  - Wiki: Wiki/index.md

hooks:
  - hooks/registry.py
paperSourceIndexFile: 'registry.md'
wikiFolder: "Wiki"

theme: 
  name: material
  features:
    - header.autohide
    - navigation.tabs

plugins:
  - search:
      separator: '[\s\-\.]+'
      indexing: 'sections'
  - tags:
      enabled: true
      tags_file: tags.md
  - blog:
      enabled: true
      blog_dir: Papers
      post_dir: "{blog}/_articles"

markdown_extensions:
  - admonition
  - tables
  - toc:
      title: On this page
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
