name: Deploy Webpage
on: [push]
permissions:
  contents: write

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nikeee/setup-pandoc@v1
      - uses: actions/setup-python@v4
      - name: install packages
        run: python -m pip install -r requirements.txt
      - name: build
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # default: public